### ISSUE TITLE
Allow creation/usage of abstract parent classes for entity classes 

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#27]
It's currently not possible to create abstract parent classes for entities, which would help avoid redundancy for entities which share a number of fields, but which don't need the parent class to exist / to be usable separately from its children.

Reason they cannot be created is that they cause an error to do with Serializers.

[Line 86](https://github.com/acdh-oeaw/apis-core-rdf/blob/6d5cc43b4d34a85d38074e76279014d87c8eb908/apis_core/helper_functions/ContentType.py#L86) in ContentType.py  suggests this problem was worked around so far by exluding classes which contain the word "abstract" in their name:

```
if (
    getattr(m, cls_n).__module__ in apis_modules
    and getattr(m, cls_n) not in lst_cont
    and cls_n.lower() not in models_exclude
    and not "abstract" in cls_n.lower()
    and inspect.isclass(getattr(m, cls_n))
):
```

Regular parent classes can currently be used in models.py, but they show up for users like any other entity (new objects can be created for them etc.) on the frontend, when the idea is to only make their children available to users.

**TODOs**
- [x] Fix error with Serializers to... #28
- [x] Filter out abstract classes from "Entities" dropdown in site main menu **– fixed in https://github.com/acdh-oeaw/apis-core-rdf/commit/c797451cf502ed0df07cb087502a6fa6a78ecec6** ([relevant line](https://github.com/acdh-oeaw/apis-core-rdf/commit/c797451cf502ed0df07cb087502a6fa6a78ecec6#diff-8c15cb13e295a1d01814007a2f491e4842756d6c88e745d9d81b6783fcb3b354L254))
- [ ] Look for other occurrences of abstract classes on the frontend + remove them where confusing/of no use to users (e.g. when they can be clicked, interacted with; simply listing them may be fine); **TODO**: search for occurrences of `AbstractEntity` class being filtered out by name
- [x] Check for potential issues with abstract classes in the context of properties:
  - [x] What happens when an abstract class is used directly in a property? **– not possible** (there are no tables to reference)
  - [x] Can their (non-abstract) children be used without problems? **– seems to be working fine**

**Comment by koeaw** [comment]
Closing this as what the issue was primarily about was solved (and it's unclear if the open task is still relevant now that so much of the code base has changed).
